const LOGIN_INPUT_CHANGE = 'user/LOGIN_INPUT_CHANGE';
const CHECK_LOGIN = 'user/CHECK_LOGIN';
const LOGIN = 'user/LOGIN';
const CHANGE_USER_INFO = 'user/CHANGE_USER_INFO';
const CHANGE_TOPIC_COLLECT = 'user/CHANGE_TOPIC_COLLECT';
const CHANGE_LOGIN_STATUS = 'user/CHANGE_LOGIN_STATUS';

export default {
  LOGIN_INPUT_CHANGE,
  CHECK_LOGIN,
  LOGIN,
  CHANGE_USER_INFO,
  CHANGE_TOPIC_COLLECT,
  CHANGE_LOGIN_STATUS,
}
